#!/bin/bash
trap "echo Take your mp3 file's"
while IFS='' read -r line || [[ -n "$line" ]]; do 
	youtube-dl $line 
done < "YoutubeURL.txt" 
find . -type f -iname "*.webm" -exec bash -c 'FILE="$1"; ffmpeg -i "${FILE}" -vn -ab 128k -ar 44100 -y "${FILE%.webm}.mp3";' _ '{}' \;
find . -type f -name "*.mkv" -exec bash -c 'FILE="$1"; ffmpeg -i "${FILE}" -vn -c:a libmp3lame -y "${FILE%.mkv}.mp3";' _ '{}' \;
